config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :sessions
  resources :places do 
    resources :recomendations
    get 'new_tweet', to: 'places#new_tweet'  
  end 
  
  root 'places#index'
  get '/auth/:provider/callback', to: 'sessions#create'

  get 'sign_out', to: 'sessions#destroy', as: :sign_out

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :place
  belongs_to :commentable, polymorphic: true
end

app/models/place.rb
class Place < ApplicationRecord
	has_many :recomendations, as: :recomend, dependent: :destroy
end

app/models/recomendation.rb
class Recomendation < ApplicationRecord
  belongs_to :place
  belongs_to :recomend, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
  	current_user.admin? unless current_user.blank?
  end	

  helper_method :current_user, :current_admin?
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :current_place, only: [:show]

  def index
    @places = Place.all
  end	

  def show
    @recomends = Recomendation.includes(:place).where(recomend_id: @place.id)
  	@recomend = Recomendation.new
  end

  def new
    @place = Place.new
  end	

  def create
  	place = Place.new(place_params)
  	if place.save
  		redirect_to place
  	else
  		render :new
  	end	
  end

  def new_tweet
    @place = Place.find(params[:place_id])
    client = Twitter::REST::Client.new do |config|
      config.consumer_key       = 'DtkMydbOtwjHPsnUZ06PGzNOD'
      config.consumer_secret    = 'PgC5hwj3Noho18ZqEcZ2D1jGP2ZGg4rGdqkRBV799lekIZycLG'
      config.oauth_token        = '849584732119728129-cu4rJGReIxTXU3NwhhD1mtVw4qpFYHc'
      config.oauth_token_secret = 'YoSoXzWZSwazxrgry5nLtxtXF11pL36EUMFoyrvVJrN1T'
    end
    recomendation = Recomendation.find_by(id: params[:format], place_id: @place.id, user_id: current_user.id)
    if recomendation
      client.update(recomendation.body.to_s+" See more on http://localhost:3000/places/#{@place.id}")
    end
      
    redirect_to @place
  end

  private

  def current_place
    @place = Place.find(params[:id])
  end	

  def place_params
  	params.require(:place).permit(:name)
  end

end

app/controllers/recomendations_controller.rb
class RecomendationsController < ApplicationController
	before_action :current_recommend, only: :destroy

  def create
    Recomendation.create(params_recomend)
    redirect_back fallback_location: root_path
  end	

  def destroy
  	@recomend.delete
  	redirect_back(fallback_location: root_path)
  end

  private

  def params_recomend
  	params.require(:recomendation).permit(:body, :mark, :recomend_type, :recomend_id, :user_id, :sender, :place_id)
  end

  def current_recommend
  	@recomend = Recomendation.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

  def create
		user = User.find_or_create_by(name: auth_params['info']['name'])
		if user.save
		  session[:user_id] = user.id
		  redirect_to root_path
		else
		  redirect_to root_path
		end    
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_path	
	end

	private

  def auth_params
    request.env['omniauth.auth']
  end

end	

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def create
		if params[:email] == 'admin@admin.com' && params[:password] == 'admin_test'
			redirect_to admin_root_path
		else
		  redirect_back(fallback_location: root_path)
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/header/_header.html.erb
<header>
  
  <div class = "container">
    
    <div class = "logo">
      <h1><a class = "mains" href = "/"> Main page</a></h1>
    </div>

    <% if current_user %>

      <div class = "nav1">

        <ul>

          <li class = 'li2'><% if current_admin? %>
            <div>
              <button id = "admin_p">Admin part</button>

              <div id = "modal">
                <div id = "enter_admin">
                  <%= form_tag User.new, :autocomplete => "off" do %>
                    <%= label_tag :email %>
                    <%= email_field_tag :email %>
                    <br/>
                    <%= label_tag :password, nil , id: 'password_tag' %>
                    <%= password_field_tag :password %>
                    <br/>
                    <%= submit_tag "Enter" %>
                  <% end %>
                </div>
              </div>
            </div>
            
            <% end %>
          </li>

          <li class = "li2", id = "header_user_link">

            <div class = "user_mini_avatar"><span class = "user_mini_avatar_text"><%= current_user.name %>

          </li>
          <li class = "li2"><div class = "header_sign_out"><%= link_to "Sign out", sign_out_path %></div></li>

        </ul>
      </div>

    <% else %>
      
      <div class = "nav1">
        <ul class = "ul2">
        	<li class = "li2", id = "header_sign_in"><%= link_to 'Tw', "/auth/twitter" %>
          
          </li> 
        </ul>
      </div>

    <%end%>

  </div>
    
</header>

<div class = "d"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'header/header' %>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= simple_form_for @place do |f| %>

  <p><%= f.input :name %></p>

  <%= f.submit %>

<% end %>

app/views/places/_recomend.html.erb
  <div>
	  <% @recomends.each do |recomend| %>

      <div>
        <%= recomend.body %>
  	    <%= recomend.sender %>
        Mark <%= recomend.mark %>
        <% if recomend.user_id == current_user.id %>
          <%= link_to 'Sent tweet', place_new_tweet_path(@place, recomend.id) %> | <%= link_to 'Delete', [@place, recomend], method: :delete %>
        <% end %>  
      </div>

	  <% end %>
  </div>

<% if current_user %> 


  <div>
    <%= simple_form_for [@place, @recomend] do |recomend| %>

      <%= recomend.hidden_field :recomend_type, value: 'Place' %>
      <%= recomend.hidden_field :recomend_id, value: @place.id %>
      <%= recomend.hidden_field :user_id, value: current_user.id %>
      <%= recomend.hidden_field :sender, value: current_user.name %>
      <%= recomend.hidden_field :place_id, value: @place.id %>

      <%= recomend.input :body %>
      <%= recomend.input :mark %>
      <p><%= recomend.submit 'Sent recomend' %></p>

    <% end %>
  </div>
<% end %>

app/views/places/index.html.erb
<h1>All places</h1>

<% if @places.empty? %>
  <h3>No one place found</h3>
<% else %>
  
  <% @places.each do |place| %>
 
    <p><%= link_to place.name, place_path(place) %></p>

  <% end %>

<% end %>   

<br/>
<%= link_to 'New place', new_place_path %> 

app/views/places/new.html.erb
<%= render 'form' %>

app/views/places/show.html.erb
<h1><%= @place.name %></h1>

<%= render 'recomend' %>